# Generated by Django 5.2.8 on 2025-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(help_text='Unique Id Assigned to Each Student', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='student_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
