# Generated by Django 6.0 on 2025-12-06 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_cameraconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('student_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='App1.student_registration')),
            ],
        ),
    ]
