# Generated by Django 6.0 on 2025-12-08 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
